MembershipApp/urls.py
from django.urls import path

from . import views

app_name = "MembershipApp"

urlpatterns = [
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request),
    path("register/", views.register),
    path("member/<username>/", views.member_profile),
    path("member/<username>/tickets/", views.tickets_view),
    path("member/<username>/vehicles/", views.vehicles_view),
    path("member/<username>/accommodations/", views.accommodations_view),
    path("member/<username>/burns/", views.burns_view),
    # path("ticket/<pk>/", views),
    path("ticket/<pk>/edit/", views.edit_ticket),
    # path("ticket/insert/", views.add_ticket),
    # path("vehicle_pass/<pk>/", views),
    path("vehicle_pass/<pk>/edit/", views.edit_vehicle),
    # path("vehicle_pass/insert/", views.add_vehicle),
    # path("accommodation/<pk>/", views),
    path("accommodation/<pk>/edit/", views.edit_accommodation),
    # path("accommodation/insert/", views.add_accommodation),
    # path("burn/<pk>/", views),
    path("burn/<pk>/edit/", views.edit_burn),
    # path("burn/insert/", views.add_burn),
    path("leader/dashboard/", views.leader_dashboard),
    path("leader/tickets/", views.leader_tables),
    path("leader/vehicles/", views.leader_tables),
    path("leader/burns/", views.leader_tables),
    path("leader/burnsaccommodations/", views.leader_burns_accommodations),
]

inventory/urls.py
from django.urls import path

from .views import *

app_name = "inventory"
urlpatterns = [
    path("", index, name="index"),
    path("<int:category_id>/", display_category, name="display_category"),
    path("<int:category_id>/add/", add_item, name="add_item"),
    path("<int:category_id>/addElectric/", add_electrical_item, name="add_electrical_item"),
    path("edit/<int:item_id>", edit_item, name="edit_item"),
    path("delete/<int:item_id>", delete_item, name="delete_item"),
]

invoices/urls.py
from django.urls import path

from . import views

app_name = "invoices"

urlpatterns = [
    path("", views.invoices_list, name="list"),
    path("add/", views.add_invoice, name="add"),
    path("<int:int>/", views.view_invoice, name="detail"),
    path("<int:int>/receipt/", views.upload_receipt, name="receipt"),
    path("export/", views.export_balance_sheet, name="export_sheet"),
]

inventory/forms.py
from django import forms

from .models import *


class AddItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            "member",
            "title",
            "description",
            "width",
            "height",
            "length",
            "quantity",
            "unit_price",
            "picture",
        ]


class AddElectricalItemForm(AddItemForm):
    class Meta:
        model = ElectricalItem
        fields = [
            "member",
            "title",
            "description",
            "width",
            "height",
            "length",
            "quantity",
            "unit_price",
            "picture",
            "voltage",
            "wattage",
        ]

MembershipApp/views.py
import datetime
import logging

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Sum
from django.http import HttpResponseNotFound, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404

from .forms import (
    BubblyMemberForm,
    MemberSearchForm,
    YearFilterForm,
    YearGroupForm,
    BurnForm,
    TicketForm,
    VehiclePassForm,
    AccommodationForm,
)
from .models import (
    Ticket,
    VehiclePass,
    BubblyMember,
    Burn,
    BurnAccommodationRelation,
    Accommodation,
    UserAccommodationRelation,
)

logger = logging.getLogger(__name__)


def leadership_required(function=None, login_url=None):
    actual_decorator = user_passes_test(lambda u: u.is_authenticated and u.is_leadership, login_url=login_url)
    if function:
        return actual_decorator(function)
    return actual_decorator


def progress_bar(model):
    burns = Burn.objects.filter(year=int(datetime.datetime.now().year))
    objects = []
    secured_object = 0
    if model == Ticket:
        for burn in burns:
            objects.append(burn.ticket)
            if burn.ticket.secured:
                secured_object += 1
        total = len(objects)
    elif model == VehiclePass:
        for burn in burns:
            objects.append(burn.vehicle_pass)
            if burn.vehicle_pass.secured:
                secured_object += 1
        total = len(objects)
    else:
        secured_object = burns.count()
        total = model.objects.all().count()
    try:
        secured_percentage = 100 * secured_object / total
        secured_number = f"{secured_object}/{total}"
    except:
        secured_percentage = 0
        secured_number = f"No {model} found"
    return secured_percentage, secured_number


def table_view(model, year, attributes_to_remove_param):
    objects = []
    secured_object = 0
    if year is None:
        burns = Burn.objects.all()
    else:
        burns = get_list_or_404(Burn, year=year)

    if model == Ticket:
        for burn in burns:
            objects.append(burn.ticket)
            if burn.ticket.secured:
                secured_object += 1
    elif model == VehiclePass:
        for burn in burns:
            objects.append(burn.vehicle_pass)
            if burn.vehicle_pass.secured:
                secured_object += 1
    else:
        objects = burns
    secured_percentage = 100 * secured_object / len(objects)
    secured_number = f"{secured_object}/{len(objects)}"
    attributes_to_remove = attributes_to_remove_param
    fields = [field.name for field in model._meta.get_fields(include_hidden=False, include_parents=True)]
    for attr in attributes_to_remove:
        if attr in fields:
            fields.remove(attr)
    return burns, objects, fields, secured_percentage, secured_number


def login_request(request):
    if not request.user.is_active:
        if request.method == "POST":
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                credentials = form.cleaned_data
                username = credentials["username"]
                password = credentials["password"]
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    member = request.user
                    if member.is_leadership:
                        return redirect("/leader/dashboard/")
                    else:
                        return redirect(f"/member/{username}")
                else:
                    logger.warning("Invalid Username or Password")
                    messages.warning(request, "Invalid Username or Password")
            else:
                logger.warning("Invalid Username or Password")
                messages.warning(request, "Invalid Username or Password")
        form = AuthenticationForm()
        return render(request=request, template_name="MembershipApp/members_login.html", context={"form": form})
    else:
        return redirect(f"/member/{request.user.username}/")


def logout_request(request):
    logout(request)
    return redirect("/login/")


def register(request):
    if request.method == "POST":
        bubbly_form = BubblyMemberForm(request.POST)
        if bubbly_form.is_valid():
            bubbly_form.save()
            return redirect("/login/")
        else:
            for msg in bubbly_form.error_messages:
                logger.warning(bubbly_form.error_messages[msg])
                messages.warning(request, bubbly_form.error_messages[msg])
            return render(
                request=request,
                template_name="MembershipApp/member_register.html",
                context={"bubbly_form": bubbly_form},
            )
    else:
        bubbly_form = BubblyMemberForm()
        return render(request, "MembershipApp/member_register.html", context={"bubbly_form": bubbly_form})


@login_required(login_url="/login/")
def member_profile(request, username):
    try:
        member = get_object_or_404(BubblyMember, username=username)
        if request.method == "POST":
            bubbly_form = BubblyMemberForm(data=request.POST, files=request.FILES, instance=member)
            if bubbly_form.is_valid():
                member.photo = request.FILES.get("photo")
                bubbly_form.save(commit=False)
                member.save()
                update_session_auth_hash(request, member)
                return redirect(f"/member/{username}/")
            else:
                for msg in bubbly_form.error_messages:
                    logger.warning(bubbly_form.error_messages[msg])
                    messages.warning(request, bubbly_form.error_messages[msg])
                return render(
                    request=request,
                    template_name="MembershipApp/member/member_profile.html",
                    context={"bubbly_form": bubbly_form},
                )
        else:
            bubbly_form = BubblyMemberForm(instance=member)
            return render(
                request, "MembershipApp/member/member_profile.html", {"member": member, "bubbly_form": bubbly_form}
            )
    except ObjectDoesNotExist as err:
        logger.warning(f"Did not find user {username}")
        return HttpResponseNotFound(f"Did not find user {username}")


@leadership_required(login_url="/login/")
def leader_dashboard(request):
    tickets_percentage, tickets_number = progress_bar(Ticket)
    vehicles_percentage, vehicles_number = progress_bar(VehiclePass)
    burn_percentage, burn_number = progress_bar(BubblyMember)

    burns = Burn.objects.filter(year=datetime.datetime.now().year)
    members = [str(i).replace("'s Burn", "") for i in burns]

    strike_deposit = list(burns.values_list("strike_deposit", flat=True))
    strike_deposit_paid = list(burns.values_list("strike_deposit_paid", flat=True))
    strike_deposit_paid = [-i for i in strike_deposit_paid]

    camp_dues = list(burns.values_list("camp_dues", flat=True))
    camp_dues_paid = list(burns.values_list("camp_dues_paid", flat=True))
    camp_dues_paid = [-i for i in camp_dues_paid]

    total_camp_dues = burns.aggregate(Sum("camp_dues"))["camp_dues__sum"]
    total_camp_dues_paid = burns.aggregate(Sum("camp_dues_paid"))["camp_dues_paid__sum"]

    if request.method == "POST":
        member_search_form = MemberSearchForm(request.POST)
        username = member_search_form.data["username"]
        return redirect(f"/member/{username}/")
    member_search_form = MemberSearchForm()
    return render(
        request=request,
        template_name="MembershipApp/leader/leader_dashboard.html",
        context={
            "member_search_form": member_search_form,
            "tickets_percentage": tickets_percentage,
            "tickets_number": tickets_number,
            "vehicles_percentage": vehicles_percentage,
            "vehicles_number": vehicles_number,
            "burn_percentage": burn_percentage,
            "burn_number": burn_number,
            "members": members,
            "camp_dues": camp_dues,
            "camp_dues_paid": camp_dues_paid,
            "strike_deposit": strike_deposit,
            "strike_deposit_paid": strike_deposit_paid,
            "total_camp_dues": total_camp_dues,
            "total_camp_dues_paid": total_camp_dues_paid,
        },
    )


@leadership_required(login_url="/login/")
def leader_tables(request):
    if request.method == "POST":
        year_form = YearFilterForm(request.POST)
        if year_form.is_valid():
            year = year_form.cleaned_data["year"]
        else:
            year = datetime.datetime.now().year
    else:
        year = datetime.datetime.now().year

    if request.path == "/leader/tickets/":
        burns, tickets, fields, secured_percentage, secured_number = table_view(Ticket, year, ["burn", "id"])

        paginator = Paginator(burns, 2)
        page = request.GET.get("page")
        try:
            burns = paginator.page(page)
        except PageNotAnInteger:
            burns = paginator.page(1)
        except EmptyPage:
            burns = paginator.page(paginator.num_pages)
        year_form = YearFilterForm()
        return render(
            request,
            "MembershipApp/leader/leader_tickets.html",
            {
                "tickets": tickets,
                "fields": fields,
                "burns": burns,
                "secured_percentage": secured_percentage,
                "secured_number": secured_number,
                "year_form": year_form,
                "year": year,
            },
        )

inventory/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from inventory.decorators import user_is_item_creator
from inventory.forms import *
from inventory.models import Item, Category, ElectricalItem


def index(request):
    categories = Category.objects.all()
    context = {"categories": categories}
    return render(request, "inventory/index.html", context)


def display_category(request, category_id):
    category = Category.objects.get(pk=category_id)
    header = "Currently Viewing " + category.name
    context = {
        "items": category.items.all().select_related("electricalitem"),
        "name": category.name,
        "header": header,
        "category_id": category_id,
        "category": category,
    }
    return render(request, "inventory/DisplayCategory.html", context)


@login_required(login_url="/member/login/")
def add_item(request, category_id):
    if request.method == "POST":
        form = AddItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save()
            category = Category.objects.get(pk=category_id)
            category.items.add(item)
            category.save()
            return redirect("inventory:index")
        else:
            return render(request, "inventory/AddItem.html", {"form": form})
    else:
        form = AddItemForm()
        return render(request, "inventory/AddItem.html", {"form": form})


@login_required(login_url="/member/login/")
def add_electrical_item(request, category_id):
    if request.method == "POST":
        form = AddElectricalItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save()
            category = Category.objects.get(pk=category_id)
            category.items.add(item)
            category.save()
            return redirect("inventory:index")
        else:
            return render(request, "inventory/AddItem.html", {"form": form})
    else:
        form = AddElectricalItemForm()
        return render(request, "inventory/AddItem.html", {"form": form})


@user_is_item_creator
def edit_item(request, item_id):
    item = Item.objects.get(pk=item_id)
    if hasattr(item, "electricalitem"):
        item = ElectricalItem.objects.get(pk=item_id)
    if request.method == "POST":
        if hasattr(item, "electricalitem"):
            form = AddElectricalItemForm(request.POST, request.FILES, instance=item)
        else:
            form = AddItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect("inventory:index")
        else:
            return render(request, "inventory/EditItem.html", {"form": form})
    else:
        if hasattr(item, "electricalitem"):
            form = AddElectricalItemForm(instance=item)
        else:
            form = AddItemForm(instance=item)
        return render(request, "inventory/EditItem.html", {"form": form})


@user_is_item_creator
def delete_item(request, item_id):
    Item.objects.filter(pk=item_id).delete()
    return redirect("inventory:index")

MembershipApp/templates/inventory/AddItem.html
{% extends 'MembershipApp/base.html' %}

{% block body %}

    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <h4>{{ header }}</h4>

            {% for field in form %}
                <div class="form-group row">
                    <label for="id_{{ field.name }}"
                           class="col-2 col-form-label">{{ field.label }} {{ field.help_text }}</label>
                    {{ field }}
                </div>
            {% endfor %}

            <div class="form-group row">
                <div class="offset-sm-2 col-sm-6">

                    <button type="submit" class="btn btn--primary type--uppercase">Add Item</button>

                </div>

            </div>
        </form>
    </div>


{% endblock %}

MembershipApp/templates/inventory/DisplayCategory.html
{% extends "MembershipApp/base.html" %}
{% load static %}
{% block header %}
    <title>{{ name }}</title>
{% endblock %}

{% block body %}
    <div class="container">
        <h3>{{ header }}</h3>
        <a href="{% url 'inventory:add_item' category.id %}" class="btn btn-sm btn-pad" role="button">Add Item</a>
        <a href="{% url 'inventory:add_electrical_item' category.id %}" class="btn btn-sm btn-pad" role="button">Add
            Electrical Item</a><br><br>

        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search.."
               style="max-width: 357px; float: right"><br><br>

        <table class="border--round table--alternate-row sortable" id="myTable">
            <thead>
            <tr>
                <th>Member</th>
                <th>Title</th>
                <th>Description</th>
                <th>Width (m)</th>
                <th>Height (m)</th>
                <th>Length (m)</th>
                <th>Quantity</th>
                <th>Unit Price ($)</th>
                <th>Picture</th>
                <th>Voltage</th>
                <th>Wattage</th>
                <th></th>
            </tr>
            </thead>

            <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item.member }}</td>
                    <td>{{ item.title }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.width }}</td>
                    <td>{{ item.height }}</td>
                    <td>{{ item.length }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.unit_price }}</td>
                    {% if item.picture %}
                        <td><a href="{{ item.picture.url }}" title="click here to see the full sized image"><img
                                src="{{ item.picture.url }}" style="width:50px;height:50px;" alt="Item"></a></td>
                    {% else %}
                        <td><i> no pic </i></td>
                    {% endif %}
                    <td>{{ item.electricalitem.voltage }}</td>
                    <td>{{ item.electricalitem.wattage }}</td>
                    <td>
                        <a href="{% url 'inventory:edit_item' item.pk %}" class="btn--xs" role="button"
                           aria-pressed="true">Edit</a>
                        <div class="modal-instance">
                            <a class="btn--xs modal-trigger" href="{% url 'inventory:delete_item' item.pk %}">
                                <span class="btn__text">
                                    Delete
                                </span>
                            </a>
                            <div class="modal-container">
                                <div class="modal-content" style="background-color: white; padding: 15px">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Delete</h5>
                                        <p> Are you sure you want to delete this item?</p>
                                        <a href="{% url 'inventory:delete_item' item.pk %}" class=" btn-sm"
                                           role="button"
                                           aria-pressed="true">Delete</a>
                                    </div>
                                </div>
                            </div>
                        </div><!--end of modal instance-->
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="{% static "MembershipApp/js/SearchTable.js" %}"></script>
    <script src="{% static "MembershipApp/js/sorttable.js" %}"></script>
{% endblock %}

MembershipApp/templates/inventory/EditItem.html
{% extends 'MembershipApp/base.html' %}
{% block body %}
    <div class="container col-md-10 edit_box">
        <form method="POST">
            {% csrf_token %}
            <h3>Editing item</h3>
            {% for field in form %}
                <div class="form-group row">
                    <label for="id_{{ field.name }}" class="col-2 col-form-label">{{ field.label }}</label>
                    <div class="col-10">

                        {{ field }}
                    </div>
                </div>
            {% endfor %}
            <div class="form-group row">
                <div class="offset-sm-2 col-sm-6">
                    <button type="submit" class="btn btn--primary type--uppercase">Save item</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

MembershipApp/templates/inventory/index.html
{% extends "MembershipApp/base.html" %}

{% block header %}
    <title>inventory</title>
{% endblock %}

{% block body %}
    <div class="container">
        <h2 style="margin-left:1%"><b>Our Inventory</b></h2>
        <h2 style="margin-left:1%">View or Add items in one of the categories</h2>

        <div class="category-container container-fluid">
            <div class="add_buttons">
                <ul>
                    <li>
                        <div class="button-group">
                            {% for category in categories %}
                                <a href="{% url 'inventory:display_category' category.id %}"
                                   class="btn btn--primary type--uppercase" role="button"
                                   style="width: 300px; color: #1b1b1b">{{ category.name }}</a>
                                <a href="{% url 'inventory:add_item' category.id %}" class="btn  btn-sm " role="button">Add
                                    Item</a>
                                <a href="{% url 'inventory:add_electrical_item' category.id %}" class="btn  btn-sm "
                                   role="button">Add Electrical Item</a><br><br>
                            {% endfor %}
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <h6 style="margin-left: 2%"><i>You can request from any admin to add a new category of items</i></h6>
    </div>

{% endblock %}