invoices/urls.py
from django.urls import path

from . import views

app_name = "invoices"

urlpatterns = [
    path("", views.invoices_list, name="list"),
    path("add/", views.add_invoice, name="add"),
    path("<int:int>/", views.view_invoice, name="detail"),
    path("<int:int>/receipt/", views.upload_receipt, name="receipt"),
    path("export/", views.export_balance_sheet, name="export_sheet"),
]

invoices/models.py
from django.conf import settings
from django.db import models

from MembershipApp.models import BubblyMember

User = settings.AUTH_USER_MODEL


# Create your models here.
class Invoice(models.Model):
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    quantity = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    receipt = models.ImageField(blank=True, null=True)
    user = models.ForeignKey(BubblyMember, on_delete=models.CASCADE, default=None)
    status = models.CharField(max_length=20, default="Pending", blank=True)

    def __str__(self):
        return self.title + " - " + self.user.__str__()

invoices/forms.py
from django import forms

from . import models


class CreateInvoice(forms.ModelForm):
    class Meta:
        model = models.Invoice
        fields = ["title", "price", "quantity"]


class UploadReceipt(forms.ModelForm):
    class Meta:
        model = models.Invoice
        fields = ["receipt"]


class SendInvoice(forms.ModelForm):
    class Meta:
        model = models.Invoice
        fields = ["title", "price", "quantity", "user"]

invoices/views.py
import csv

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect

from . import forms
from .models import Invoice


# Create your views here.
@login_required(login_url="/member/login")
def invoices_list(request):
    if request.user.is_leadership:
        invoices = Invoice.objects.order_by("date")
        temp = 0
        for i in invoices:
            temp = temp + i.price * i.quantity

        return render(request, "invoices/lead_invoices_list.html", {"invoices": invoices, "temp": temp})
    else:
        # invoices = Invoice.objects.filter(user=request.user).filter(Q(receipt='')|Q(receipt=None)).order_by('date')
        invoices = Invoice.objects.filter(user=request.user).order_by("date")
        temp = 0
        for i in invoices:
            temp = temp + i.price * i.quantity

        return render(request, "invoices/invoices_list.html", {"invoices": invoices, "temp": temp})


@login_required(login_url="/member/login")
def add_invoice(request):
    if request.user.is_leadership:
        if request.method == "POST":
            form = forms.SendInvoice(request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                return redirect("invoices:list")
        else:
            form = forms.SendInvoice()
        return render(request, "invoices/lead_invoice_add.html", {"form": form})
    else:
        if request.method == "POST":
            form = forms.CreateInvoice(request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.user = request.user
                instance.save()
                return redirect("invoices:list")
        else:
            form = forms.CreateInvoice()
        return render(request, "invoices/invoice_add.html", {"form": form})


def view_invoice(request, int):
    if request.user.is_leadership:
        invoice = Invoice.objects.get(id=int)
        if invoice.receipt == "":
            name = request.user.get_full_name()
            return render(request, "invoices/lead_pending_invoice_details.html", {"invoice": invoice, "name": name})
        else:
            invoice = Invoice.objects.get(id=int)
            name = request.user.get_full_name()
            return render(request, "invoices/lead_invoice_details.html", {"invoice": invoice, "name": name})
    else:
        invoice = Invoice.objects.get(id=int)
        if invoice.receipt == "":
            invoice = Invoice.objects.get(id=int)
            name = request.user.get_full_name()
            return render(request, "invoices/invoice_details.html", {"invoice": invoice, "name": name})
        else:
            invoice = Invoice.objects.get(id=int)
            name = request.user.get_full_name()
            return render(request, "invoices/invoice_completed_details.html", {"invoice": invoice, "name": name})


@login_required(login_url="/member/login")
def upload_receipt(request, int):
    if request.method == "POST":
        form = forms.UploadReceipt(request.POST, request.FILES)
        if form.is_valid():
            m = Invoice.objects.get(id=int)
            m.receipt = form.cleaned_data["receipt"]
            m.status = "Completed"
            m.save()
            return redirect("invoices:list")


@login_required(login_url="/member/login")
def export_balance_sheet(request):
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = 'attachement; filename="balance_sheet.csv"'

    writer = csv.writer(response)
    writer.writerow(["Name", "Quantity", "Price", "Total"])

    invoices = Invoice.objects.filter(user=request.user).filter(Q(receipt="") | Q(receipt=None)).order_by("date")

    sum = 0

    for i in invoices:
        sum = sum + i.price * i.quantity

    for invoice in invoices:
        writer.writerow(
            [invoice.title, invoice.quantity, "$" + str(invoice.price), "$" + str(invoice.price * invoice.quantity)]
        )

    writer.writerow(["Total Cost", "", "", "$" + str(sum)])

    return response

invoices/templates/invoices/invoice_add.html
{% extends "MembershipApp/base.html" %}
<!DOCTYPE html>
{% load static %}
{% block body %}
<html lang="en">
    <link rel="stylesheet" type="text/css" href="{% static 'css/form_style.css' %}">
<form class="site-form" action="{% url 'invoices:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Add">
</form>

</html>
{% endblock %}

invoices/templates/invoices/invoice_completed_details.html
{% extends "MembershipApp/base.html" %}
{% load static %}
{% block body %}
<html>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style_details.css' %}">
			<h1>Invoice</h1>
			<!--<address>
				<br>
				101 E. Chapman Ave
                Orange, CA 92866
				(800) 555-1234
			</address>-->
		<article>
			<h1>Recipient</h1>
			<address contenteditable>
				<p>Bubble Ever After<br>{{invoice.user}}</p>
			</address>
			<table class="meta">
				<tr>
					<th>Invoice #</th>
					<td>{{invoice.id}}</td>
				</tr>
				<tr>
					<th>Date</th>
					<td>{{invoice.date}}</td>
				</tr>
				<tr>
					<th>Amount Due</th>
					<td>${% widthratio invoice.quantity 1 invoice.price %}</td>
				</tr>
			</table>
			<table class="inventory">
				<thead>
					<tr>
						<th>Item</th>
                        <th>Quantity</th>
						<th>Price</th>
						<th>Total</th>
						<th>Settle Invoice</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>{{invoice.title}}</td>
                        <td>{{invoice.quantity}}</td>
						<td>${{invoice.price}}</td>
						<td>${% widthratio invoice.quantity 1 invoice.price %}</td>
                        <td><a href="{{invoice.receipt.url}}">View the Uploaded Receipt</a> </td>
					</tr>
				</tbody>
			</table>

			<!--<a class="add">+</a>
			<table class="balance">
				<tr>
					<th><span contenteditable>Total</span></th>
					<td><span data-prefix>$</span><span>600.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Amount Paid</span></th>
					<td><span data-prefix>$</span><span contenteditable>0.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Balance Due</span></th>
					<td><span data-prefix>$</span><span>600.00</span></td>
				</tr>
			</table>-->
		</article>
</html>
{% endblock %}

invoices/templates/invoices/invoice_details.html
{% extends "MembershipApp/base.html" %}
{% load static %}
{% block body %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/style_details.css' %}">
			<h1>Invoice</h1>
			<!--<address>
				<br>
				101 E. Chapman Ave
                Orange, CA 92866
				(800) 555-1234
			</address>-->
		<article>
			<h1>Recipient</h1>
			<address contenteditable>
				<p>Bubble Ever After<br>{{invoice.user}}</p>
			</address>
			<table class="meta">
				<tr>
					<th>Invoice #</th>
					<td>{{invoice.id}}</td>
				</tr>
				<tr>
					<th>Date</th>
					<td>{{invoice.date}}</td>
				</tr>
				<tr>
					<th>Amount Due</th>
					<td>${% widthratio invoice.quantity 1 invoice.price %}</td>
				</tr>
			</table>
            <form action="{% url 'invoices:receipt' int=invoice.id %}" method="post" enctype="multipart/form-data">
			<table class="inventory">
				<thead>
					<tr>
						<th>Item</th>
                        <th>Quantity</th>
						<th>Price</th>
						<th>Total</th>
						<th>Settle Invoice</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>{{invoice.title}}</td>
                        <td>{{invoice.quantity}}</td>
						<td>${{invoice.price}}</td>
						<td>${% widthratio invoice.quantity 1 invoice.price %}</td>
                            <td>
                        {% csrf_token %}
                                <input id="id_image" type="file" class="inputfile" name="receipt">
                                <label for="id_image">Choose a file</label>
                            </td>
					</tr>
				</tbody>
			</table>
            <input type="submit" class="sub" value="Submit"/>
</form>
			<!--<a class="add">+</a>
			<table class="balance">
				<tr>
					<th><span contenteditable>Total</span></th>
					<td><span data-prefix>$</span><span>600.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Amount Paid</span></th>
					<td><span data-prefix>$</span><span contenteditable>0.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Balance Due</span></th>
					<td><span data-prefix>$</span><span>600.00</span></td>
				</tr>
			</table>-->
		</article>

<!--<form action="{% url 'invoices:receipt' int=invoice.id %}" method="post" enctype="multipart/form-data">


        <input id="id_image" type="file" class="" name="receipt">

    <input type="submit" value="Submit" />
</form>-->

{% endblock %}

invoices/templates/invoices/invoices_list.html
{% extends "MembershipApp/base.html" %}
{% load static %}
{% block body %}
    <meta charset="utf-8">
    <title>InvoiceList</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


<table>
    <thead>
    <tr>
        <th scope="col">Date</th>
        <th scope="col">Order ID</th>
        <th scope="col">Name</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">Total</th>
        <th scope="col">Action</th>
        <th scope="col">Status</th>

    </tr>
    </thead>
    <tbody>
    {% for invoice in invoices %}
        <tr>
            <td><strong class="item-date">{{ invoice.date }}</strong></td>
            <td class="item-id">{{ invoice.id }}</td>
            <td class="item-name">{{ invoice.title }}</td>
            <td class="item-quantity">{{ invoice.quantity }}</td>
            <td class="item-price">${{ invoice.price }}</td>
            <td class="item-total">${% widthratio invoice.quantity 1 invoice.price %}</td>
            <td><a href="{% url 'invoices:detail' int=invoice.id %}" class="view-invoice">View Invoice</a></td>
            <td class="item-status">{{ invoice.status }}</td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    <tr>
        <td colspan="5">Total Cost</td>
        <td>${{ temp }}</td>
    </tr>
    </tfoot>
</table>
<a href="add" class="button button1">Add Invoice</a>
<a href="export" class="button button1">Export Balance Sheet in Excel Format</a>
{% endblock %}

invoices/templates/invoices/lead_invoice_add.html
{% extends "MembershipApp/base.html" %}
{% load static %}
{% block body %}
    <div class="container">
        <link rel="stylesheet" type="text/css" href="{% static 'css/form_style.css' %}">
        <form class="site-form" action="{% url 'invoices:add' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Send">
        </form>
    </div>
{% endblock %}

invoices/templates/invoices/lead_invoice_details.html
{% load static %}
{% block body %}
<html>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style_details.css' %}">
			<h1>Invoice</h1>
			<!--<address>
				<br>
				101 E. Chapman Ave
                Orange, CA 92866
				(800) 555-1234
			</address>-->
		<article>
			<h1>Recipient</h1>
			<address contenteditable>
				<p>Bubble Ever After<br>{{invoice.user}}</p>
			</address>
			<table class="meta">
				<tr>
					<th>Invoice #</th>
					<td>{{invoice.id}}</td>
				</tr>
				<tr>
					<th>Date</th>
					<td>{{invoice.date}}</td>
				</tr>
				<tr>
					<th>Amount Due</th>
					<td>${% widthratio invoice.quantity 1 invoice.price %}</td>
				</tr>
			</table>
            <form action="{% url 'invoices:receipt' int=invoice.id %}" method="post" enctype="multipart/form-data">
			<table class="inventory">
				<thead>
					<tr>
						<th>Item</th>
                        <th>Quantity</th>
						<th>Price</th>
                        <th>Total</th>
                        <th>Settle Invoice</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ invoice.title }}</td>
                    <td>{{ invoice.quantity }}</td>
                    <td>${{ invoice.price }}</td>
                    <td>${% widthratio invoice.quantity 1 invoice.price %}</td>
                    <td><a style="color: #3e7cc2" href="{{ invoice.receipt.url }}">View Receipt</a></td>
                </tr>
                </tbody>
            </table>
                <!--<a class="add">+</a>
                <table class="balance">
                    <tr>
                        <th><span contenteditable>Total</span></th>
                        <td><span data-prefix>$</span><span>600.00</span></td>
                    </tr>
                    <tr>
                        <th><span contenteditable>Amount Paid</span></th>
                        <td><span data-prefix>$</span><span contenteditable>0.00</span></td>
                    </tr>
                    <tr>
                        <th><span contenteditable>Balance Due</span></th>
                        <td><span data-prefix>$</span><span>600.00</span></td>
                    </tr>
                </table>-->


<!--<form action="{% url 'invoices:receipt' int=invoice.id %}" method="post" enctype="multipart/form-data">


        <input id="id_image" type="file" class="" name="receipt">

    <input type="submit" value="Submit" />
</form>-->
</html>
{% endblock %}

invoices/templates/invoices/lead_invoices_list.html
{% extends "MembershipApp/base.html" %}
{% load static %}
{% block body %}
    <div class="container">
        <meta charset="utf-8">
        <title>InvoiceList</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


        <table>
            <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Order ID</th>
                <th scope="col">Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Total</th>
                <th scope="col">Action</th>
                <th scope="col">Status</th>
                <th scope="col">Member</th>

            </tr>
            </thead>
            <tbody>
            {% for invoice in invoices %}
                <tr>
                    <td><strong class="item-date">{{ invoice.date }}</strong></td>
                    <td class="item-id">{{ invoice.id }}</td>
                    <td class="item-name">{{ invoice.title }}</td>
                    <td class="item-quantity">{{ invoice.quantity }}</td>
                    <td class="item-price">${{ invoice.price }}</td>
                    <td class="item-total">${% widthratio invoice.quantity 1 invoice.price %}</td>
                    <td><a href="{% url 'invoices:detail' int=invoice.id %}" class="view-invoice">View Invoice</a></td>
                    <td class="item-status">{{ invoice.status }}</td>
                    <td class="item-status">{{ invoice.user }}</td>

                </tr>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <td colspan="5">Total Cost</td>
                <td>${{ temp }}</td>
            </tr>
            </tfoot>
        </table>
        <a href="add" class="button button1">Send Invoice</a>
        <a href="export" class="button button1">Export</a>
    </div>
{% endblock %}

invoices/templates/invoices/lead_pending_invoice_details.html
{% load static %}
{% block body %}
<html>
		<link rel="stylesheet" type="text/css" href="{% static 'css/style_details.css' %}">
			<h1>Invoice</h1>
			<!--<address>
				<br>
				101 E. Chapman Ave
                Orange, CA 92866
				(800) 555-1234
			</address>-->
		<article>
			<h1>Recipient</h1>
			<address contenteditable>
				<p>Bubble Ever After<br>{{invoice.user}}</p>
			</address>
			<table class="meta">
				<tr>
					<th>Invoice #</th>
					<td>{{invoice.id}}</td>
				</tr>
				<tr>
					<th>Date</th>
					<td>{{invoice.date}}</td>
				</tr>
				<tr>
					<th>Amount Due</th>
					<td>${% widthratio invoice.quantity 1 invoice.price %}</td>
				</tr>
			</table>
            <form action="{% url 'invoices:receipt' int=invoice.id %}" method="post" enctype="multipart/form-data">
			<table class="inventory">
				<thead>
					<tr>
						<th>Item</th>
                        <th>Quantity</th>
						<th>Price</th>
						<th>Total</th>
						<th>Settle Invoice</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>{{invoice.title}}</td>
                        <td>{{invoice.quantity}}</td>
						<td>${{invoice.price}}</td>
						<td>${% widthratio invoice.quantity 1 invoice.price %}</td>
                        <td>The member hasn't paid yet</td>
					</tr>
				</tbody>
			</table>
			<!--<a class="add">+</a>
			<table class="balance">
				<tr>
					<th><span contenteditable>Total</span></th>
					<td><span data-prefix>$</span><span>600.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Amount Paid</span></th>
					<td><span data-prefix>$</span><span contenteditable>0.00</span></td>
				</tr>
				<tr>
					<th><span contenteditable>Balance Due</span></th>
					<td><span data-prefix>$</span><span>600.00</span></td>
				</tr>
			</table>-->


<!--<form action="{% url 'invoices:receipt' int=invoice.id %}" method="post" enctype="multipart/form-data">


        <input id="id_image" type="file" class="" name="receipt">

    <input type="submit" value="Submit" />
</form>-->
</html>
{% endblock %}